import Database from "better-sqlite3";
import {afterEach,beforeEach,describe,expect,it} from "vitest";
import fs from "node:fs";import os from "node:os";import path from "node:path";
import {CURRENT_SCHEMA_VERSION,openDb,type Db} from "../src/db.js";
import {edgesFrom,featuresForFile,getSetting,listTerritories,readSpec,retrieveKnowledge,setSetting} from "../src/graph-store.js";
import {KnowledgeService} from "../src/knowledge-service.js";import {upsertRepo} from "../src/team-store.js";import {seedActiveMapping} from "./kb-fixtures.js";
const T0="2026-07-12T10:00:00.000Z";

describe("GraphStore read-model facade",()=>{let dir:string,db:Db;beforeEach(()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),"vh-graph-read-"));db=openDb(path.join(dir,"db"));upsertRepo(db,"/repo",null,"main",T0);});afterEach(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});
  it("derives territories and active mapping anchors without a production write helper",()=>{seedActiveMapping(db,1,[{id:"orders",name:"Orders",anchors:[{file:"src/orders/index.ts"}]},{id:"orders/flow",parentId:"orders",name:"Flow",anchors:[{file:"src/orders/flow.ts"},{file:"src/orders/flow.ts",symbol:"guard"}]},{id:"auth",name:"Auth",anchors:[{file:"src/auth.ts"}]}],T0);expect(listTerritories(db,1)).toEqual([{id:"auth",name:"Auth",anchoredFileCount:1,subBlocks:[]},{id:"orders",name:"Orders",anchoredFileCount:2,subBlocks:[{id:"orders/flow",name:"Flow",anchoredFileCount:1}]}]);expect(featuresForFile(db,1,"src/auth.ts")).toEqual(["auth"]);expect(featuresForFile(db,1,"missing.ts")).toEqual([]);});
  it("reads canonical rows written only through KnowledgeService",()=>{const svc=new KnowledgeService(db);const ctx={actor:"test",taskId:"t",requestId:"r",now:T0};svc.applyDraftBatch(1,{idempotencyKey:"seed",specs:[{id:"context-a",type:"context",summary:"active truth",evidence:[{sourceType:"test",sourceRef:"t",evidenceRef:"t"}]}]},ctx);expect(readSpec(db,1,"context-a")?.state).toBe("draft");expect(retrieveKnowledge(db,1,{query:"truth"})).toEqual([]);svc.mutate(1,"promote",{specId:"context-a",idempotencyKey:"p"},ctx);expect(retrieveKnowledge(db,1,{query:"truth"})[0]?.spec.id).toBe("context-a");expect(edgesFrom(db,"context-a",1)).toEqual([]);});
  it("keeps settings as the configuration-domain writer",()=>{setSetting(db,"theme","dark");setSetting(db,"theme","light",1);expect(getSetting(db,"theme",1)).toBe("light");expect(getSetting(db,"theme",2)).toBe("dark");});
});

describe("migration ladder",()=>{let dir:string;beforeEach(()=>{dir=fs.mkdtempSync(path.join(os.tmpdir(),"vibehub-mig-"));});afterEach(()=>fs.rmSync(dir,{recursive:true,force:true}));
  it("fresh db lands on latest version with immutable provenance",()=>{const db=openDb(path.join(dir,"t.db"));expect(db.pragma("user_version",{simple:true})).toBe(CURRENT_SCHEMA_VERSION);expect(()=>db.prepare(`INSERT INTO repos(root_path,default_branch,created_at) VALUES('/r','main',?)`).run(T0)).not.toThrow();db.prepare(`INSERT INTO kb_provenance_events(repo_id,operation,actor,request_id,at,payload) VALUES(1,'x','a','r',?,'{}')`).run(T0);expect(()=>db.prepare(`UPDATE kb_provenance_events SET actor='b'`).run()).toThrow(/immutable/);expect(()=>db.prepare(`DELETE FROM kb_provenance_events`).run()).toThrow(/immutable/);db.close();});
  it("a v1 database upgrades in place keeping data",()=>{const p=path.join(dir,"old.db"),raw=new Database(p);raw.exec(`CREATE TABLE repos(id INTEGER PRIMARY KEY,root_path TEXT NOT NULL UNIQUE,slug TEXT,default_branch TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE sync_state(repo_id INTEGER PRIMARY KEY REFERENCES repos(id),last_fetch_at TEXT,last_fetch_ok INTEGER,gh_available INTEGER NOT NULL DEFAULT 0,repo_files INTEGER,last_synced_at TEXT);CREATE TABLE team_branches(repo_id INTEGER NOT NULL,name TEXT NOT NULL,head_sha TEXT NOT NULL,last_commit_at TEXT NOT NULL,last_author TEXT NOT NULL DEFAULT '',ahead INTEGER NOT NULL DEFAULT 0,behind INTEGER NOT NULL DEFAULT 0,merged INTEGER NOT NULL DEFAULT 0,pr_number INTEGER,pr_state TEXT,pr_title TEXT,PRIMARY KEY(repo_id,name));CREATE TABLE team_branch_files(repo_id INTEGER NOT NULL,branch TEXT NOT NULL,path TEXT NOT NULL,change_kind TEXT NOT NULL,PRIMARY KEY(repo_id,branch,path));CREATE TABLE team_conflicts(repo_id INTEGER NOT NULL,branch_a TEXT NOT NULL,branch_b TEXT NOT NULL,path TEXT NOT NULL,first_detected_at TEXT NOT NULL,last_seen_at TEXT NOT NULL,PRIMARY KEY(repo_id,branch_a,branch_b,path));INSERT INTO repos(root_path,slug,default_branch,created_at) VALUES('/repo','o/n','main','${T0}');PRAGMA user_version=1;`);raw.close();const db=openDb(p);expect(db.pragma("user_version",{simple:true})).toBe(CURRENT_SCHEMA_VERSION);expect((db.prepare(`SELECT slug FROM repos`).get() as {slug:string}).slug).toBe("o/n");expect(db.prepare(`SELECT COUNT(*) n FROM tasks`).get()).toEqual({n:0});db.close();});
  it("a real v6 database upgrades repo-scoped receipts without loss",()=>{const p=path.join(dir,"v6.db"),raw=new Database(p);raw.exec(`CREATE TABLE repos(id INTEGER PRIMARY KEY,root_path TEXT NOT NULL UNIQUE,slug TEXT,default_branch TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE tasks(id TEXT PRIMARY KEY);CREATE TABLE sessions(id TEXT PRIMARY KEY);CREATE TABLE events(id INTEGER PRIMARY KEY,repo_id INTEGER NOT NULL REFERENCES repos(id),task_id TEXT REFERENCES tasks(id),session_id TEXT REFERENCES sessions(id),type TEXT NOT NULL CHECK(type IN('launch','self_report','file_change','file_read','test_run','user_injection','agent_ack','question','cross_read_notice','commit','state_transition')),at TEXT NOT NULL,payload TEXT NOT NULL CHECK(json_valid(payload)));CREATE INDEX idx_events_task_at ON events(task_id,at);CREATE TABLE intervention_requests(request_id TEXT PRIMARY KEY,repo_id INTEGER NOT NULL REFERENCES repos(id),result TEXT NOT NULL CHECK(json_valid(result)),created_at TEXT NOT NULL);CREATE INDEX idx_intervention_requests_repo ON intervention_requests(repo_id,created_at);INSERT INTO repos VALUES(1,'/one','o/one','main','${T0}');INSERT INTO repos VALUES(2,'/two','o/two','main','${T0}');INSERT INTO tasks VALUES('task');INSERT INTO sessions VALUES('session');PRAGMA user_version=6;`);const receipt=JSON.stringify({requestId:"same",outcome:"applied"}),payload=JSON.stringify({id:"e",at:T0,type:"self_report",text:"legacy"});raw.prepare(`INSERT INTO intervention_requests VALUES('same',1,?,?)`).run(receipt,T0);raw.prepare(`INSERT INTO events VALUES(41,1,'task','session','self_report',?,?)`).run(T0,payload);raw.close();const db=openDb(p);expect(db.prepare(`SELECT repo_id,request_id,input_hash inputHash,result,created_at FROM intervention_requests`).get()).toEqual({repo_id:1,request_id:"same",inputHash:"legacy-unverifiable:1:same",result:receipt,created_at:T0});expect(db.prepare(`SELECT id,payload FROM events`).get()).toEqual({id:41,payload});expect(()=>db.prepare(`INSERT INTO intervention_requests(repo_id,request_id,input_hash,result,created_at) VALUES(2,'same','new-hash','{}','${T0}')`).run()).not.toThrow();db.close();});
});
