/** Read-only compatibility/read-model facade after the KB v2 cutover. */
import type {TerritoryLayout,SubBlock,Territory} from "./contract/map-types.js";
import type {Db} from "./db.js";import {canonicalRepoPath} from "./scope-registry.js";

export function listTerritories(db:Db,repoId:number):Territory[]{const features=db.prepare(`SELECT f.feature_id id,f.parent_feature_id parentId,f.name FROM repo_active_mapping a JOIN mapping_version_features f ON f.repo_id=a.repo_id AND f.version_id=a.version_id WHERE f.repo_id=? AND f.lifecycle='active' ORDER BY f.name`).all(repoId) as Array<{id:string;parentId:string|null;name:string}>;const countStmt=db.prepare(`SELECT COUNT(DISTINCT a.file) n FROM mapping_version_anchors a JOIN repo_active_mapping active ON active.repo_id=a.repo_id AND active.version_id=a.version_id WHERE a.repo_id=? AND (a.feature_id=? OR a.feature_id IN(SELECT f.feature_id FROM mapping_version_features f WHERE f.repo_id=active.repo_id AND f.version_id=active.version_id AND f.parent_feature_id=?))`);const count=(id:string)=>(countStmt.get(repoId,id,id) as {n:number}).n;return features.filter(x=>x.parentId===null).map(t=>{const subBlocks:SubBlock[]=features.filter(x=>x.parentId===t.id).map(s=>({id:s.id,name:s.name,anchoredFileCount:count(s.id)}));return{id:t.id,name:t.name,anchoredFileCount:count(t.id),subBlocks};});}
export function readTerritoryLayouts(db:Db,repoId:number):Map<string,TerritoryLayout>{const rows=db.prepare(`SELECT l.feature_id id,l.pct_left leftPct,l.pct_top topPct,l.pct_width widthPct,l.pct_height heightPct FROM mapping_version_layouts l JOIN repo_active_mapping a ON a.repo_id=l.repo_id AND a.version_id=l.version_id WHERE l.repo_id=?`).all(repoId) as Array<{id:string;leftPct:number;topPct:number;widthPct:number;heightPct:number}>;return new Map(rows.map(r=>[r.id,{left:r.leftPct,top:r.topPct,width:r.widthPct,height:r.heightPct}]));}
export function countAnchoredFiles(db:Db,repoId:number):number{return(db.prepare(`SELECT COUNT(DISTINCT a.file) n FROM mapping_version_anchors a JOIN repo_active_mapping active ON active.repo_id=a.repo_id AND active.version_id=a.version_id WHERE a.repo_id=?`).get(repoId) as {n:number}).n;}
export function featuresForFile(db:Db,repoId:number,file:string):string[]{return(db.prepare(`SELECT DISTINCT a.feature_id id FROM mapping_version_anchors a JOIN repo_active_mapping active ON active.repo_id=a.repo_id AND active.version_id=a.version_id WHERE a.repo_id=? AND a.file=?`).all(repoId,canonicalRepoPath(file)) as Array<{id:string}>).map(x=>x.id);}

export interface SpecRow{id:string;repoId:number;featureId:string|null;type:"intent"|"decision"|"constraint"|"convention"|"contract"|"context"|"change";state:"draft"|"active"|"stale"|"superseded"|"deprecated";summary:string;detail:string|null}
export type SpecType=SpecRow["type"];
export interface KnowledgeResult{spec:SpecRow;matchedPaths:string[];score:number;sourceKind:"canonical"}
/** @deprecated New adapters use KnowledgeService.searchSpecs. */
export function retrieveKnowledge(db:Db,repoId:number,input:{query?:string;paths?:string[];limit?:number;includeDrafts?:boolean;includeHistory?:boolean}):KnowledgeResult[]{assertGraphSemanticAuthority(db,repoId);const terms=(input.query??"").toLowerCase().split(/\s+/).filter(Boolean),paths=(input.paths??[]).map(canonicalRepoPath);const states=["active",...(input.includeDrafts?["draft"]:[]),...(input.includeHistory?["stale","superseded","deprecated"]:[])];const params:unknown[]=[repoId,...states];const clauses=[`s.repo_id=?`,`s.state IN (${states.map(()=>"?").join(",")})`];if(terms.length)for(const t of terms){clauses.push(`lower(r.summary||' '||COALESCE(r.detail,'')) LIKE ?`);params.push(`%${t}%`);}if(paths.length){clauses.push(`EXISTS(SELECT 1 FROM kb_spec_current_anchors a WHERE a.repo_id=s.repo_id AND a.spec_id=s.spec_id AND (${paths.map(()=>`a.file=? OR a.file LIKE ?||'/%'`).join(" OR ")}))`);for(const p of paths)params.push(p,p);}const rows=db.prepare(`SELECT s.spec_id id,s.repo_id repoId,s.feature_id featureId,r.type,s.state,r.summary,r.detail FROM kb_specs s JOIN kb_spec_revisions r ON r.repo_id=s.repo_id AND r.spec_id=s.spec_id AND r.revision=s.current_revision WHERE ${clauses.join(" AND ")} ORDER BY s.spec_id LIMIT ?`).all(...params,Math.min(input.limit??8,50)) as SpecRow[];return rows.map(spec=>{const anchored=(db.prepare(`SELECT file FROM kb_spec_current_anchors WHERE repo_id=? AND spec_id=?`).all(repoId,spec.id) as Array<{file:string}>).map(x=>x.file);const matchedPaths=paths.filter(p=>anchored.some(a=>a===p||a.startsWith(`${p}/`)));const hay=`${spec.summary} ${spec.detail??""}`.toLowerCase();return{spec,matchedPaths,score:matchedPaths.length*100+terms.reduce((n,t)=>n+(hay.includes(t)?10:0),0),sourceKind:"canonical"};});}

export function readSpec(db:Db,repoId:number,id:string):SpecRow|null;
/** @deprecated Pass repoId explicitly. */export function readSpec(db:Db,id:string):SpecRow|null;
export function readSpec(db:Db,repoIdOrId:number|string,maybeId?:string):SpecRow|null{let repoId:number,id:string;if(typeof repoIdOrId==="number"){repoId=repoIdOrId;id=maybeId!;}else{assertNoImplicitMigratedRepo(db);id=repoIdOrId;const owners=db.prepare(`SELECT repo_id repoId FROM kb_specs WHERE spec_id=? ORDER BY repo_id`).all(id) as Array<{repoId:number}>;if(owners.length!==1)return null;repoId=owners[0]!.repoId;}assertGraphSemanticAuthority(db,repoId);return(db.prepare(`SELECT s.spec_id id,s.repo_id repoId,s.feature_id featureId,r.type,s.state,r.summary,r.detail FROM kb_specs s JOIN kb_spec_revisions r ON r.repo_id=s.repo_id AND r.spec_id=s.spec_id AND r.revision=s.current_revision WHERE s.repo_id=? AND s.spec_id=?`).get(repoId,id) as SpecRow|undefined)??null;}
export function edgesFrom(db:Db,fromId:string,repoId?:number):Array<{toId:string;type:string}>{if(repoId===undefined){assertNoImplicitMigratedRepo(db);const repos=db.prepare(`SELECT repo_id repoId FROM kb_specs WHERE spec_id=?`).all(fromId) as Array<{repoId:number}>;if(repos.length!==1)return[];repoId=repos[0]!.repoId;}assertGraphSemanticAuthority(db,repoId);const rows=db.prepare(`SELECT to_spec_id toId,type FROM kb_spec_relations WHERE repo_id=? AND from_spec_id=?`).all(repoId,fromId) as Array<{toId:string;type:string}>;const placement=db.prepare(`SELECT feature_id toId FROM kb_specs WHERE repo_id=? AND spec_id=? AND feature_id IS NOT NULL`).get(repoId,fromId) as {toId:string}|undefined;if(placement)rows.push({toId:placement.toId,type:"belongs_to"});return rows;}

function assertGraphSemanticAuthority(db:Db,repoId:number):void{if(db.prepare(`SELECT 1 FROM repo_semantic_authority WHERE repo_id=?`).get(repoId))throw new Error("Git semantic authority requires the repository-aware OperationDispatcher");}
function assertNoImplicitMigratedRepo(db:Db):void{if(db.prepare(`SELECT 1 FROM repo_semantic_authority LIMIT 1`).get())throw new Error("implicit repository semantic reads are forbidden after Git authority cutover");}

export function setSetting(db:Db,key:string,value:string,repoId=0):void{db.prepare(`INSERT INTO settings(repo_id,key,value) VALUES(?,?,?) ON CONFLICT(repo_id,key) DO UPDATE SET value=excluded.value`).run(repoId,key,value);}
export function getSetting(db:Db,key:string,repoId=0):string|null{return(db.prepare(`SELECT value FROM settings WHERE key=? AND repo_id IN(?,0) ORDER BY repo_id DESC LIMIT 1`).get(key,repoId) as {value:string}|undefined)?.value??null;}
